/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatchMatchIdRouteImport } from './routes/match.$matchId'
import { Route as ApiPublicRunScanNowRouteImport } from './routes/api/public/run-scan-now'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchMatchIdRoute = MatchMatchIdRouteImport.update({
  id: '/match/$matchId',
  path: '/match/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRunScanNowRoute = ApiPublicRunScanNowRouteImport.update({
  id: '/api/public/run-scan-now',
  path: '/api/public/run-scan-now',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/matches': typeof MatchesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/api/public/run-scan-now': typeof ApiPublicRunScanNowRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/matches': typeof MatchesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/api/public/run-scan-now': typeof ApiPublicRunScanNowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/matches': typeof MatchesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/api/public/run-scan-now': typeof ApiPublicRunScanNowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/matches'
    | '/sitemap.xml'
    | '/match/$matchId'
    | '/api/public/run-scan-now'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/matches'
    | '/sitemap.xml'
    | '/match/$matchId'
    | '/api/public/run-scan-now'
  id:
    | '__root__'
    | '/'
    | '/matches'
    | '/sitemap.xml'
    | '/match/$matchId'
    | '/api/public/run-scan-now'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MatchesRoute: typeof MatchesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  MatchMatchIdRoute: typeof MatchMatchIdRoute
  ApiPublicRunScanNowRoute: typeof ApiPublicRunScanNowRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$matchId': {
      id: '/match/$matchId'
      path: '/match/$matchId'
      fullPath: '/match/$matchId'
      preLoaderRoute: typeof MatchMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/run-scan-now': {
      id: '/api/public/run-scan-now'
      path: '/api/public/run-scan-now'
      fullPath: '/api/public/run-scan-now'
      preLoaderRoute: typeof ApiPublicRunScanNowRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MatchesRoute: MatchesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  MatchMatchIdRoute: MatchMatchIdRoute,
  ApiPublicRunScanNowRoute: ApiPublicRunScanNowRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
